"""
ROSAMA Consultancy — Google Fonts Self-Hosting Script
Run this once from the rosama-consultancy-website folder:
    python download_fonts.py

It will:
  1. Fetch the Google Fonts CSS (using a modern browser User-Agent to get woff2 files)
  2. Download every .woff2 font file into assets/vendor/fonts/
  3. Write assets/vendor/fonts/fonts.css pointing to the local files
"""

import os
import re
import urllib.request

FONTS_URL = (
    "https://fonts.googleapis.com/css2?"
    "family=Poppins:wght@300;400;500;600;700;800"
    "&family=Roboto:wght@300;400;500"
    "&display=swap"
)

# Chrome UA — tells Google Fonts to return woff2 (smallest, best format)
CHROME_UA = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
    "AppleWebKit/537.36 (KHTML, like Gecko) "
    "Chrome/124.0.0.0 Safari/537.36"
)

OUT_DIR = os.path.join("assets", "vendor", "fonts")

def fetch_text(url, ua=None):
    req = urllib.request.Request(url)
    if ua:
        req.add_header("User-Agent", ua)
    with urllib.request.urlopen(req, timeout=20) as r:
        return r.read().decode("utf-8")

def fetch_binary(url):
    req = urllib.request.Request(url)
    req.add_header("User-Agent", CHROME_UA)
    with urllib.request.urlopen(req, timeout=20) as r:
        return r.read()

def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    print(f"Created folder: {OUT_DIR}")

    print("Fetching Google Fonts CSS ...")
    css = fetch_text(FONTS_URL, CHROME_UA)

    # Extract all @font-face blocks
    blocks = re.findall(r'@font-face\s*\{[^}]+\}', css, re.DOTALL)
    if not blocks:
        print("ERROR: No @font-face blocks found. Check the URL or user-agent.")
        return

    local_css_rules = []
    downloaded = 0

    for block in blocks:
        # Get font-family, style, weight
        family  = re.search(r"font-family:\s*'([^']+)'", block)
        style   = re.search(r"font-style:\s*(\w+)",     block)
        weight  = re.search(r"font-weight:\s*(\d+)",    block)
        src_url = re.search(r"url\((https://[^)]+)\)",  block)
        display = re.search(r"font-display:\s*(\w+)",   block)

        if not (family and weight and src_url):
            continue

        family_name  = family.group(1)   # e.g. Poppins
        weight_val   = weight.group(1)   # e.g. 400
        style_val    = style.group(1) if style else "normal"
        display_val  = display.group(1) if display else "swap"
        remote_url   = src_url.group(1)  # https://fonts.gstatic.com/...

        # Detect format from extension
        ext = remote_url.rsplit(".", 1)[-1].split("?")[0]  # woff2 / ttf
        fmt_map = {"woff2": "woff2", "woff": "woff", "ttf": "truetype"}
        fmt = fmt_map.get(ext, ext)

        # Build local filename:  poppins-400-normal.woff2
        fname = f"{family_name.lower()}-{weight_val}-{style_val}.{ext}"
        fpath = os.path.join(OUT_DIR, fname)

        if os.path.exists(fpath):
            print(f"  SKIP  {fname} (already exists)")
        else:
            print(f"  DL    {fname} ...", end=" ", flush=True)
            data = fetch_binary(remote_url)
            with open(fpath, "wb") as f:
                f.write(data)
            print(f"{len(data)//1024} KB")
            downloaded += 1

        local_src = f"url('fonts/{fname}') format('{fmt}')"

        rule = (
            "@font-face {\n"
            f"  font-family: '{family_name}';\n"
            f"  font-style: {style_val};\n"
            f"  font-weight: {weight_val};\n"
            f"  font-display: {display_val};\n"
            f"  src: {local_src};\n"
            "}"
        )
        local_css_rules.append(rule)

    # Write fonts.css
    css_out = os.path.join(OUT_DIR, "fonts.css")
    with open(css_out, "w", encoding="utf-8") as f:
        f.write("/* Self-hosted fonts — generated by download_fonts.py */\n\n")
        f.write("\n\n".join(local_css_rules))
        f.write("\n")

    print(f"\nDone! Downloaded {downloaded} font file(s).")
    print(f"CSS written to: {css_out}")
    print("\nNext: commit and push the assets/vendor/fonts/ folder to GitHub.")

if __name__ == "__main__":
    main()
